import ENV from './environment';

export const COMETCHAT_CONSTANTS = {
    APP_ID: ENV.COMETCHAT_APP_ID,
    AUTH_KEY: ENV.COMETCHAT_AUTH_KEY,
    API_KEY: ENV.COMETCHAT_API_KEY,
    REGION: ENV.COMETCHAT_REGION,
};